imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
   
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FosUser Configuration
fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: Utilisateurs\UtilisateursBundle\Entity\Utilisateurs
    registration:
        form:
            type: ornoir_user_registration  
        confirmation:
            enabled: true
    profile: 
        form:
            type: ornoir_pro_profile
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

# knp_paginator Configuration
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
        
# liip_imagine Configuration
liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
                
        produitThumb:
            quality: 80
            filters:
                thumbnail: { size: [350, 350], mode: inset }
        
        produitphare:
            quality: 85
            filters:
                thumbnail: { size: [270, 490], mode: inset  }
        
              
        produitpopulaire:
            quality: 85
            filters:
                thumbnail: { size: [370, 370], mode: inset  }
        
        produitAllThumb:
            quality: 80
            filters:
                thumbnail: { size: [254, 290], mode: inset }
                
        produitThumbMenu:
            quality: 80
            filters:
                thumbnail: { size: [300, 300], mode: inset }
                
        produitThumbDetail:
            quality: 100
            filters:
                thumbnail: { size: [557, 557], mode: inset }
                
        produitThumbItem:
            quality: 100
            filters:
                thumbnail: { size: [117, 117], mode: inset }
                
        produitLastThumb:
            quality: 80
            filters:
                thumbnail: { size: [140, 140], mode: inset }
                
        produitCommentaireThumb:
            quality: 80
            filters:
                thumbnail: { size: [100, 100], mode: inset }
        
        cartThumbItem:
            quality: 100
            filters:
                thumbnail: { size: [115, 115], mode: inset }
        
        PanierLogo:
            quality: 100
            filters:
                thumbnail: { size: [55, 55], mode: inset }
                
        cartThumbMenuItem:
            quality: 100
            filters:
                thumbnail: { size: [75, 75], mode: inset }
        
        rechercheThumbItem:
            quality: 100
            filters:
                thumbnail: { size: [35, 35], mode: inset }
                
        recherche2ThumbItem:
            quality: 100
            filters:
                thumbnail: { size: [50, 50], mode: inset }
                
        MotifThumb:
            quality: 95
            filters:
                thumbnail: { size: [40, 40], mode: inset }
                
        wishlistThumbItem:
            quality: 100
            filters:
                thumbnail: { size: [110, 110], mode: inset }
                
        compareThumbItem:
            quality: 100
            filters:
                thumbnail: { size: [110, 110], mode: inset }
        
        photoProfil:
            quality: 95
            filters:
                thumbnail: { size: [195, 195], mode: inset }
                
        marqueLogoThumb:
            quality: 95
            filters:
                thumbnail: { size: [25, 25], mode: inset }
                
        imagesMarquesThumb:
            quality: 95
            filters:
                thumbnail: { size: [35, 35], mode: inset }
        
        marquePhotoProfil:
            quality: 100
            filters:
                thumbnail: { size: [323, 242], mode: inset }
                
        photoProfilThumb:
            quality: 95
            filters:
                thumbnail: { size: [20, 20], mode: inset }
                
        commandeThumb:
            quality: 85
            filters:
                thumbnail: { size: [200, 200], mode: inset  }