kountac_homepage:
    path:     /homepage
    defaults: { _controller: KountacBundle:Homepage:index }
    
kountac_homepage_index:
    path:     /
    defaults: { _controller: KountacBundle:Homepage:index }
    
pages:
    path:     /page/{valeur}
    defaults: { _controller: KountacBundle:PagesAdmin:affiche }

kountac_newsletter:
    path:   /newsletter_subscribe
    defaults: { _controller: KountacBundle:Menu:newsletterFooter }
    
kountac_panier:
    resource: "@KountacBundle/Resources/config/routingPanier.yml"
    prefix:   /Cart/

kountac_devise:
    resource: "@KountacBundle/Resources/config/routingDevise.yml"
    prefix:   /Devise/
    
kountac_wishlist:
    resource: "@KountacBundle/Resources/config/routingWishlist.yml"
    prefix:   /Wishlist/
    
kountac_compare:
    resource: "@KountacBundle/Resources/config/routingCompare.yml"
    prefix:   /Compare/
    
kountac_produits:
    resource: "@KountacBundle/Resources/config/routingProduits.yml"
    prefix:   /Product/
    
kountac_reservations:
    resource: "@KountacBundle/Resources/config/routingReservations.yml"
    prefix:   /Reserve/
    
kountac_adminCategories:
    resource: "@KountacBundle/Resources/config/routingAdmin/categories.yml"
    prefix:   /admin/adminCategories/
    
kountac_adminCollections:
    resource: "@KountacBundle/Resources/config/routingAdmin/collections.yml"
    prefix:   /admin/adminCollections/
 
kountac_adminCommandes:
    resource: "@KountacBundle/Resources/config/routingAdmin/commandes.yml"
    prefix:   /admin/adminCommandes/
    
kountac_adminProduits:
    resource: "@KountacBundle/Resources/config/routingAdmin/produits.yml"
    prefix:   /admin/adminProduits/
    
kountac_adminAchats:
    resource: "@KountacBundle/Resources/config/routingAdmin/achats.yml"
    prefix:   /admin/adminAchats/
    
kountac_adminNewsletters:
    resource: "@KountacBundle/Resources/config/routingAdmin/newsletters.yml"
    prefix:   /admin/Newsletters/
    
kountac_adminPages:
    resource: "@KountacBundle/Resources/config/routingAdmin/pages.yml"
    prefix:   /admin/Pages/