all_products:
    path:     /all/
    defaults: { _controller: KountacBundle:Produit:allProducts }
    
recherche_avatar:
    path:     /avatar/find
    defaults: { _controller: KountacBundle:Produit:recherche_avatar }
    
recherche_taille_poids:
    path:     /taille/find
    defaults: { _controller: KountacBundle:Produit:recherche_taillePoids }

quickViewAllProducts:
    path:     /quickView_all/{id}/
    defaults: { _controller: KountacBundle:Produit:quickViewAllProducts }
    
quickView:
    path:     /quickView/{id}/
    defaults: { _controller: KountacBundle:Produit:quickVue }

quickViewEspaceMarque:
    path:     /quickView_marque/{id}/
    defaults: { _controller: KountacBundle:Produit:quickViewEspaceMarque }
    
espace_marque:
    path:     /mark_space/{id}
    defaults: { _controller: KountacBundle:Produit:espace_marque }
    
recherche_avatar_marque:
    path:     /mark_space_avatar/find_{id}
    defaults: { _controller: KountacBundle:Produit:recherche_avatarMarque }
    
recherche_taille_poids_marque:
    path:     /mark_space_taille/find_{id}
    defaults: { _controller: KountacBundle:Produit:recherche_taillePoidsMarque }
    
product:
    path:     /single/{id}/
    defaults: { _controller: KountacBundle:Produit:product }
    
product_mannequin:
    path:     /single_mannequin/{id}_{id_image}/
    defaults: { _controller: KountacBundle:Produit:productMannequin }
       
categorie_2:
    path:     /catalog_2/{categorie}/
    defaults: { _controller: KountacBundle:Produit:categorie_2 }
    
categorie_1:
    path:     /catalog_1/{categorie}/
    defaults: { _controller: KountacBundle:Produit:categorie_1 }

new_categorie:
    path:     /catalog_new/{categorie}/
    defaults: { _controller: KountacBundle:Menu:new }
    
    
best_categorie:
    path:     /catalog_destockage/{categorie}/
    defaults: { _controller: KountacBundle:Menu:destockage }
    
collection:
    path:     /collection/{collection}/
    defaults: { _controller: KountacBundle:Produit:collection }

precommande:
    path:     /precommand/{precommande}/
    defaults: { _controller: KountacBundle:Precommande:precommandes }

######  Gestion destockage  ######
#Femmes

femmes_destockage:
    path:     /destockagesFemmes/
    defaults: { _controller: KountacBundle:DestockageCategorie:femmes }
    
femmes_destockageHauts:
    path:     /destockagesFemmes_Hauts/
    defaults: { _controller: KountacBundle:DestockageCategorie:femmesHauts }
    
femmes_destockageBas:
    path:     /destockagesFemmes_Bas/
    defaults: { _controller: KountacBundle:DestockageCategorie:femmesBas }
    
femmes_destockageEnsembles:
    path:     /destockagesFemmes_Ensembles/
    defaults: { _controller: KountacBundle:DestockageCategorie:femmesEnsembles }
 
#Hommes
hommes_destockage:
    path:     /destockagesHommes/
    defaults: { _controller: KountacBundle:DestockageCategorie:hommes }
    
hommes_destockageHauts:
    path:     /destockagesHommes_Hauts/
    defaults: { _controller: KountacBundle:DestockageCategorie:hommesHauts }
    
hommes_destockageBas:
    path:     /destockagesHommes_Bas/
    defaults: { _controller: KountacBundle:DestockageCategorie:hommesBas }
    
hommes_destockageEnsembles:
    path:     /destockagesHommes_Ensembles/
    defaults: { _controller: KountacBundle:DestockageCategorie:hommesEnsembles }

#Enfants
enfants_destockage:
    path:     /destockagesEnfants/
    defaults: { _controller: KountacBundle:DestockageCategorie:enfants }
    
enfants_destockageHauts:
    path:     /destockagesEnfants_Hauts/
    defaults: { _controller: KountacBundle:DestockageCategorie:enfantsHauts }
    
enfants_destockageBas:
    path:     /destockagesEnfants_Bas/
    defaults: { _controller: KountacBundle:DestockageCategorie:enfantsBas }
    
enfants_destockageEnsembles:
    path:     /destockagesEnfants_Ensembles/
    defaults: { _controller: KountacBundle:DestockageCategorie:enfantsEnsembles }

######  Gestion sur mesure  ######
#Femmes
femmes_surmesure:
    path:     /surmesureFemmes/
    defaults: { _controller: KountacBundle:SurMesuresCategorie:femmes }
    
femmes_surmesureHauts:
    path:     /surmesureFemmes_Hauts/
    defaults: { _controller: KountacBundle:SurMesuresCategorie:femmesHauts }
    
femmes_surmesureBas:
    path:     /surmesureFemmes_Bas/
    defaults: { _controller: KountacBundle:SurMesuresCategorie:femmesBas }

femmes_surmesureEnsembles:
    path:     /surmesureFemmes_Ensembles/
    defaults: { _controller: KountacBundle:SurMesuresCategorie:femmesEnsembles }

#Hommes
hommes_surmesure:
    path:     /surmesureHommes/
    defaults: { _controller: KountacBundle:SurMesuresCategorie:hommes }
    
hommes_surmesureHauts:
    path:     /surmesureHommes_Hauts/
    defaults: { _controller: KountacBundle:SurMesuresCategorie:hommesHauts }
    
hommes_surmesureBas:
    path:     /surmesureHommes_Bas/
    defaults: { _controller: KountacBundle:SurMesuresCategorie:hommesBas }

hommes_surmesureEnsembles:
    path:     /surmesureHommes_Ensembles/
    defaults: { _controller: KountacBundle:SurMesuresCategorie:hommesEnsembles }

#Enfants
enfants_surmesure:
    path:     /surmesureEnfants/
    defaults: { _controller: KountacBundle:SurMesuresCategorie:enfants }
    
enfants_surmesureHauts:
    path:     /surmesureEnfants_Hauts/
    defaults: { _controller: KountacBundle:SurMesuresCategorie:enfantsHauts }
    
enfants_surmesureBas:
    path:     /surmesureEnfants_Bas/
    defaults: { _controller: KountacBundle:SurMesuresCategorie:enfantsBas }

enfants_surmesureEnsembles:
    path:     /surmesureEnfants_Ensembles/
    defaults: { _controller: KountacBundle:SurMesuresCategorie:enfantsEnsembles }
    

sur_mesures_categories:
    path:     /sur_mesures/{surmesure}/
    defaults: { _controller: KountacBundle:SurMesuresCategorie:surMesuresCat }
    
new_sur_mesures_categories:
    path:     /sur_mesures_news/
    defaults: { _controller: KountacBundle:SurMesuresCategorie:new }
    
best_sur_mesures_categories:
    path:     /sur_mesures_soldes/
    defaults: { _controller: KountacBundle:SurMesuresCategorie:best }
    
rechercheProduits:
    pattern: /find
    defaults: { _controller: KountacBundle:Produit:rechercheTraitement } 