produit_pro_index:
    path:     /
    defaults: { _controller: "UtilisateursBundle:ProduitPro:index" }
    methods:  GET
    
produit_pro_new_1:
    path:     /new_1
    defaults: { _controller: "UtilisateursBundle:ProduitPro:new1" }
    methods:  [GET, POST]
    
produit_pro_new_edit1:
    path:     /new_edit_1{id}
    defaults: { _controller: "UtilisateursBundle:ProduitPro:new_edit1" }
    methods:  [GET, POST]
    
produit_pro_new_2:
    path:     /new_2_{id}
    defaults: { _controller: "UtilisateursBundle:ProduitPro:new2" }
    methods:  [GET, POST]
    
produit_pro_new_edit2:
    path:     /new_edit_2{id}
    defaults: { _controller: "UtilisateursBundle:ProduitPro:new_edit2" }
    methods:  [GET, POST]
    
produit_pro_new_mannequin:
    path:     /new_mannequin_{id}
    defaults: { _controller: "UtilisateursBundle:ProduitPro:addMannequin" }
    methods:  [GET, POST]
    
produit_pro_new_images_mannequin:
    path:     /new_images_mannequin_{id}
    defaults: { _controller: "UtilisateursBundle:ProduitPro:addImagesMannequin" }
    methods:  [GET, POST]
    
produit_pro_edit_images_mannequin:
    path:     /edit_images_mannequin_{id}
    defaults: { _controller: "UtilisateursBundle:Formulaires:addImagesMannequin" }
    methods:  [GET, POST]
    
produit_pro_set_images_top_new:
    path:     /set_images_mannequin_Newtop{id}
    defaults: { _controller: "UtilisateursBundle:ProduitPro:setTopMannequinNewProduit" }
    methods:  [GET, POST]

produit_pro_set_images_top:
    path:     /set_images_mannequin_top{id}
    defaults: { _controller: "UtilisateursBundle:ProduitPro:setTopMannequin" }
    methods:  [GET, POST]
    
produit_pro_new_motif:
    path:     /new_pro_motif
    defaults: { _controller: "UtilisateursBundle:ProduitPro:addNewMotif" }
    methods:  [GET, POST]

produit_pro_new_3:
    path:     /new_3_{id}
    defaults: { _controller: "UtilisateursBundle:ProduitPro:new3" }
    methods:  [GET, POST]
    
produit_pro_new_edit3:
    path:     /new_edit_3{id}
    defaults: { _controller: "UtilisateursBundle:ProduitPro:new_edit3" }
    methods:  [GET, POST]
    
produit_pro_new_delete_image:
    path:     /newDelete_image{id}
    defaults: { _controller: "UtilisateursBundle:ProduitPro:deleteNewImages" }
    methods:  [GET, POST]
    
produit_pro_new_4:
    path:     /new_4_{id}
    defaults: { _controller: "UtilisateursBundle:ProduitPro:new4" }
    methods:  [GET, POST]

produit_pro_new_resume:
    path:     /new_resume_{id}
    defaults: { _controller: "UtilisateursBundle:ProduitPro:newResume" }
    methods:  [GET, POST]

produit_pro_show:
    path:     /{id}/show
    defaults: { _controller: "UtilisateursBundle:ProduitPro:show" }
    methods:  [GET, POST]

produit_pro_edit_1:
    path:     /{id}/edit_1
    defaults: { _controller: "UtilisateursBundle:ProduitPro:edit_1" }
    methods:  [GET, POST]
    
produit_pro_edit_2:
    path:     /{id}/edit_2
    defaults: { _controller: "UtilisateursBundle:ProduitPro:edit_2" }
    methods:  [GET, POST]
    
produit_pro_edit_21:
    path:     /{id}/edit_21
    defaults: { _controller: "UtilisateursBundle:ProduitPro:edit_21" }
    methods:  [GET, POST]
    
produit_pro_edit_3:
    path:     /{id}/edit_3
    defaults: { _controller: "UtilisateursBundle:ProduitPro:edit_3" }
    methods:  [GET, POST]
    
produit_pro_edit_31:
    path:     /{id}/edit_31
    defaults: { _controller: "UtilisateursBundle:ProduitPro:edit_31" }
    methods:  [GET, POST]
    
produit_pro_edit_pays:
    path:     /{id}/edit_pays
    defaults: { _controller: "UtilisateursBundle:ProduitPro:editPays" }
    methods:  [GET, POST]

produit_pro_delete:
    path:     /{id}/delete
    defaults: { _controller: "UtilisateursBundle:ProduitPro:delete" }
    
produit_pro_delete_motif:
    path:     /{id}/delete_motif
    defaults: { _controller: "UtilisateursBundle:ProduitPro:deleteMotif" }
    
produit_pro_delete_images:
    path:     /{id}/delete_images
    defaults: { _controller: "UtilisateursBundle:ProduitPro:deleteImages" }
    
produit_pro_stock_epuise:
    path:     /stock_épuisé
    defaults: { _controller: "UtilisateursBundle:ProduitPro:stock" }
    methods:  GET
    
produit_pro_sale:
    path:     /product_sales
    defaults: { _controller: "UtilisateursBundle:ProduitPro:sale" }
    methods:  GET
    
